[book]
authors = ["Contexts and capabilities Members"]
language = "en"
multilingual = false
src = "."
title = "Contexts and capabilities initiative"

[output.html]
no-section-label=true
git-repository-url="https://github.com/nikomatsakis/contexts-capabilities-initiative"
edit-url-template="https://github.com/nikomatsakis/contexts-capabilities-initiative/edit/master/{path}"
site-url="/contexts-capabilities-initiative/"

[output.html.fold]
enable = true
level = 0
